package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"betterpg/graph/model"
	"context"
	"fmt"
)

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todo - todo"))
}

// Name is the resolver for the name field.
func (r *todoResolver) Name(ctx context.Context, obj *model.Todo) (string, error) {
	panic(fmt.Errorf("not implemented: Name - name"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Todo returns TodoResolver implementation.
func (r *Resolver) Todo() TodoResolver { return &todoResolver{r} }

type queryResolver struct{ *Resolver }
type todoResolver struct{ *Resolver }
