package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	"fmt"
	"logrocket/graph/model"
	"strconv"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	id := strconv.Itoa(len(r.todos))

	// CREATE A NEW TODO
	todo := &model.Todo{
		Text: input.Text,
		ID:   id,
		User: &model.User{ID: input.UserID, Name: "user " + input.UserID},
	}
	// ADD THE TODO TO THE TODOS ARRAY
	r.todos = append(r.todos, todo)
	// RETURN THE TODO
	return todo, nil
}

// CreateDog is the resolver for the createDog field.
func (r *mutationResolver) CreateDog(ctx context.Context, input model.NewDog) (*model.Dog, error) {
	panic(fmt.Errorf("not implemented: CreateDog - createDog"))
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	// RETURN ALL THE TODOS
	return r.todos, nil
}

// Dogs is the resolver for the dogs field.
func (r *queryResolver) Dogs(ctx context.Context) ([]*model.Dog, error) {
	panic(fmt.Errorf("not implemented: Dogs - dogs"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
