// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewNinja struct {
	Name           *string `json:"name,omitempty"`
	Rank           *string `json:"rank,omitempty"`
	MainStyle      *string `json:"mainStyle,omitempty"`
	Village        *string `json:"village,omitempty"`
	Status         *string `json:"status,omitempty"`
	NumberOfJutsus *int    `json:"numberOfJutsus,omitempty"`
}

type Ninja struct {
	Name           *string `json:"name,omitempty"`
	Rank           *string `json:"rank,omitempty"`
	MainStyle      *string `json:"mainStyle,omitempty"`
	Village        *string `json:"village,omitempty"`
	Status         *string `json:"status,omitempty"`
	NumberOfJutsus *int    `json:"numberOfJutsus,omitempty"`
}

type ResponseMessage struct {
	Message string `json:"message"`
}
