// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Todo struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type ID struct {
	ID string `json:"id"`
}

type Newid struct {
	ID string `json:"id"`
}
