// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Team struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Members []*User `json:"members"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
